import React from "react";
import Head from "next/head";
import Header from "../header/header";
import { Container } from "@chakra-ui/react";
// import Image from "next/image";

const Layout = ({ children, title }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Container maxW="1300px">{children}</Container>
      </main>
    </>
  );
};

export default Layout;
